=== lzq888/paparazzi-linux-release/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (depend?,header,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT depend EMPTY>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event (handler*)>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (flag|file|define|raw)*>
<!ELEMENT flag EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT raw (#PCDATA)>

<!ATTLIST module
name CDATA #REQUIRED>

<!ATTLIST depend
require CDATA #IMPLIED
conflict CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED >

<!ATTLIST event
fun CDATA #REQUIRED>

<!ATTLIST handler
fun CDATA #REQUIRED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED>

<!ATTLIST makefile
target CDATA "ap|sim">

<!ATTLIST flag
name CDATA #REQUIRED
value CDATA #IMPLIED>

<!ATTLIST file
name CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #REQUIRED>

=== lzq888/paparazzi-linux-release/conf/modules/demo_module.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="demo_module">
  <header>
    <file name="demo_module.h"/>
  </header>
  <init fun="init_demo()"/>
  <periodic fun="periodic_1Hz_demo()" freq="1." start="start_demo()" stop="stop_demo()" autorun="TRUE"/>
  <periodic fun="periodic_10Hz_demo()" period="0.1" start="start_demo()" stop="stop_demo()" autorun="FALSE"/>
  <makefile>
    <raw>
#Exemple of RAW makefile part
    </raw>
    <flag name="DEMO_MODULE_LED" value="2"/>
    <file name="demo_module.c"/>
  </makefile>
</module>

=== lzq888/paparazzi-linux-release/conf/modules/formation_flight.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="multi">
  <header>
    <file name="formation.h"/>
  </header>
  <init fun="formation_init()"/>
  <datalink message="FORMATION_STATUS" fun="ParseFormationStatus()"/>
  <datalink message="FORMATION_SLOT" fun="ParseFormationSlot()"/>
  <makefile>
    <file name="formation.c"/>
  </makefile>
</module>

=== lzq888/paparazzi-linux-release/conf/modules/gsm.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="gsm">
  <header>
    <file name="gsm.h"/>
  </header>
  <init fun="gsm_init()"/>
  <periodic fun="gsm_periodic_1Hz()" period="1." start="gsm_start()" stop="gsm_stop()"/>
  <periodic fun="gsm_send_report()" period="60."/>
  <event fun="gsm_event()"/>
  <makefile>
    <file name="gsm.c"/>
  </makefile>
</module>
